apiVersion: v1
kind: Service
metadata:
  name: mongo-kanister
  namespace: <VM namespace>
spec:
  selector:
    vm.kubevirt.io/name: <VM name>
  ports:
  - name: mongodb
    protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP
