apiVersion: v1
kind: Service
metadata:
  name: mongo-kanister
  namespace: ocpv-rhel9
spec:
  selector:
    vm.kubevirt.io/name: rhel-10
  ports:
  - name: mongodb
    protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP
